#!/bin/sh

touch /etc/config/captive-portal

# Only initialize once
uci -q get captive-portal.@service[0].daemon >/dev/null 2>&1 && exit 0

uci -q batch <<'EOF'
add captive-portal service
set captive-portal.@service[-1].daemon='nodogsplash'
set captive-portal.@service[-1].interface='lan'
set captive-portal.@service[-1].auth_method='both'
set captive-portal.@service[-1].portal_name='Guest WiFi'
set captive-portal.@service[-1].max_client_time='0'
set captive-portal.@service[-1].gatewayname='CaptivePortal'
set captive-portal.@service[-1].default_upload_limit='0'
set captive-portal.@service[-1].default_download_limit='0'
set captive-portal.@service[-1].default_timeout='1200'

add captive-portal guest
set captive-portal.@guest[-1].username='guestuser'
set captive-portal.@guest[-1].password='ph4hhw0rDd'
set captive-portal.@guest[-1].mac=''
set captive-portal.@guest[-1].upload_limit='0'
set captive-portal.@guest[-1].download_limit='0'
set captive-portal.@guest[-1].timeout='1200'
set captive-portal.@guest[-1].auth_method='password'
set captive-portal.@guest[-1].enabled='1'

commit captive-portal
EOF

exit 0
